# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation

name: Java CI with Maven

on:
  push:
    branches: [ "main", "feature1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: |
         echo "catting /home/runner/.m2/toolchains.xml"
         cat /home/runner/.m2/toolchains.xml
         echo
         echo "catting /home/runner/.m2/settings.xml"
         cat /home/runner/.m2/settings.xml
         echo
         echo "env variables"
         env
         echo "catting pom.xml"
         cat pom.xml
         echo "m2 cache size"
         du -sh ~/.m2/repository
         echo "--------------------"
         echo
    
